### ISSUE TITLE
just a couple of questions

### ISSUE THREAD

**Issue by dkwo** [tenllado/dotfiles#1]
Does this setup work with U2F token and Google's Advanced Protection Program?
Does the python script work with python3?

Thanks.

**Comment by tenllado** [comment]
Sorry, I cannot see which script are you referring to, is it perhaps oauth2.py. That is not mine. I think it should work with python3 but I am not sure. I also don't know what is the U2F token and Google's Advanced Protection Program. Sorry for that, I cannot help you.

**Comment by dkwo** [comment]
No worries.
I was talking about oauth2.py, which looks like it needs python2, but I 
ma be wrong.

Thanks.
